id: P67F68B86
initial_creation_type: ocr
source_metadata:
  volumes:
    457b6e3f2ae44daea2644ff1fd69ea5b:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: །དད་སྐྱེད་སྒོན་མ་བཞུགས་སོ།།
      total_pages: 1144
      volume_number: 96
