id: D4F778637
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-23T10:32:33+00:00'
last_modified: '2022-05-30T04:28:09.208958+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '4797':
      image_group_id: I1PD95941
      title: །དད་སྐྱེད་སྒོན་མ་བཞུགས་སོ།།
      total_pages: 1144
      order: 96
      base_file: 4797.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
